name: generate-summary-cards
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          user: shehablotfallah
          template: github_dark
